katalog/urls.py
from django.urls import path
from katalog import views

urlpatterns = [
    path("", views.get_catalog_items, name="get_catalog_items")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist import views

app_name = "todolist"

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("create-task/", views.create_task, name="create_task"),
    path("toggle-task/<int:id>", views.toggle_task, name="toggle_task"),
    path("delete-task/<int:id>", views.delete_task, name="delete_task"),
    path("json/", views.get_json_todolist, name="json"),
    path("add/", views.create_task_ajax, name="create_task_ajax"),
    path("delete/<int:id>", views.delete_task_ajax, name="delete_task_ajax"),
]

todolist/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description"]

todolist/views.py
import json
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Task
from .forms import TaskForm
from django.core import serializers
from django.http import HttpResponse, HttpResponseBadRequest

# Create your views here.
@login_required(login_url="/todolist/login/")
def home(request):
    tasks = Task.objects.filter(user=request.user).order_by("is_finished")
    done_tasks = Task.objects.filter(user=request.user, is_finished=True).count()

    context = {"tasks": tasks, "done_tasks": done_tasks, "user": request.user}
    return render(request, "todolist/home.html", context)


def register_user(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Akun telah berhasil dibuat!")
            return redirect("todolist:login")

    context = {"form": form}
    return render(request, "todolist/register.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/todolist/")
        else:
            messages.info(request, "Username atau password salah!")

    return render(request, "todolist/login.html")


def logout_user(request):
    logout(request)
    return redirect("todolist:login")


@login_required(login_url="/todolist/login/")
def create_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect("/todolist")

    context = {"form": form}
    return render(request, "todolist/create_task.html", context)


@login_required(login_url="/todolist/login/")
def delete_task(request, id):
    task = Task.objects.filter(pk=id, user=request.user).first()
    if task:
        task.delete()
        return redirect("/todolist")
    messages.error(request, "An error occurred while deleting the task.")
    return redirect("/todolist")


@login_required(login_url="/todolist/login/")
def create_task_ajax(request):
    if (
        request.headers.get("x-requested-with") == "XMLHttpRequest"
        and request.method == "POST"
    ):
        form = TaskForm(request.POST)
        if form.is_valid:
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            data = serializers.serialize(
                "json",
                [
                    new_task,
                ],
            )
            struct = json.loads(data)
            data = json.dumps(struct[0])
            return HttpResponse(data, content_type="application/json")
    return HttpResponseBadRequest("An error occured.")


@login_required(login_url="/todolist/login/")
def delete_task_ajax(request, id):
    if (
        request.headers.get("x-requested-with") == "XMLHttpRequest"
        and request.method == "DELETE"
    ):
        task = Task.objects.filter(pk=id, user=request.user).first()
        if task:
            task.delete()
            tasks = Task.objects.filter(user=request.user)
            return HttpResponse(
                serializers.serialize("json", tasks), content_type="application/json"
            )
    return HttpResponseBadRequest("An error occured.")


@login_required(login_url="/todolist/login/")
def toggle_task(request, id):
    if (
        request.headers.get("x-requested-with") == "XMLHttpRequest"
        and request.method == "POST"
    ):
        task = Task.objects.filter(pk=id, user=request.user).first()
        if task:
            task.is_finished = False if task.is_finished else True
            task.save()
            data = serializers.serialize(
                "json",
                [
                    task,
                ],
            )
            struct = json.loads(data)
            data = json.dumps(struct[0])
            return HttpResponse(data, content_type="application/json")
        messages.error(request, "An error occurred while editing the task.")
    return HttpResponseBadRequest("An error occured.")


@login_required(login_url="/todolist/login")
def get_json_todolist(request):
    tasks = Task.objects.filter(user=request.user).order_by("is_finished")
    return HttpResponse(
        serializers.serialize("json", tasks), content_type="application/json"
    )

todolist/templates/todolist/create_task.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block meta %}
<title>Buat To Do | To Do List</title>
{% endblock meta %}


{% block content %}
<nav class="bg-black text-white px-6 py-4 flex justify-between items-center sticky top-0">
    <p class="text-2xl font-bold">To Do List</p>
    <div class="flex justify-center items-center gap-6">
        <strong>Halo, {{ user.username }}!</strong>
        <a class="px-4 py-2 bg-red-600 rounded-lg" href="{% url 'todolist:logout' %}">Logout</a>
    </div>
 </nav>
 
 <section class="flex flex-col items-center justify-center h-screen">
    <p class="text-2xl font-bold mb-4">Buat To Do Baru</p>  

    <form method="POST">
        {% csrf_token %} 
        {% for field in form %}
        <div>
            {{ field.errors }}
            {{ field.label_tag }}<br>
            {{ field | add_class:"w-full border-2 border-black rounded-lg mb-3" }}
        </div>
        {% endfor %}
        <input class="w-full px-4 py-2 bg-black text-white rounded-lg cursor-pointer" type="submit" name="submit" value="Tambah"/>
        </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </section>  

{% endblock content %}

todolist/templates/todolist/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Halo, {{ user.username }}! | To Do List</title>
{% endblock meta %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        const makeTaskCard = (task) => {
            const taskDate = new Date(`${task.fields.date}`)
            const formattedTaskDate = new Intl.DateTimeFormat('id-ID', { dateStyle: 'long', timeStyle: 'short' }).format(taskDate)
            const taskSection = document.querySelector(".tasks")
            taskSection.insertAdjacentHTML('beforeend', 
                `<div id="task-${task.pk}" class="hover:scale-105 duration-75 border-2 border-black w-1/2 p-6 mb-8 rounded-lg flex flex-col md:flex-row gap-8 justify-between items-center ${task.fields.is_finished ? "border-green-600" : "border-red-600"}">
                    <div id="task-${task.pk}-text" class="text-center md:text-left flex flex-col justify-between gap-8 w-3/4 ${task.fields.is_finished && "line-through decoration-slate-500"}">
                        <div>
                            <p class="text-lg font-bold mb-2">${task.fields.title}</p>
                            <p class="text-slate-400">${task.fields.description}</p>
                        </div>
                        <p class="text-sm flex justify-center md:justify-end">${formattedTaskDate}</p>
                    </div>
                    <div class="w-full text-center flex flex-col gap-2 md:w-1/4">
                        <button id="toggle-task-btn" class="px-4 py-2 bg-black text-white rounded-lg w-full" onclick=toggleTask(${task.pk})>Ubah Status</button>
                        <button id="delete-task-btn" class="px-4 py-2 border-2 border-red-600 bg-white text-red-600 rounded-lg w-full" onclick=deleteTask(${task.pk})>Hapus</button>
                    </div>
                </div>`
            )
        }

        const getTasks = () => {
            $.ajax(
                {
                    type: "GET",
                    url: "{% url 'todolist:json' %}",
                    dataType: "json",
                    success: (tasks) => {
                        if (tasks.length == 0) {
                            const taskSection = document.querySelector(".tasks")
                            taskSection.insertAdjacentHTML('beforeend', 
                                `<div class="animation my-4 grid place-items-center">
                                    <lottie-player src="https://assets9.lottiefiles.com/datafiles/vhvOcuUkH41HdrL/data.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                                    <p>Waduh, kamu belum punya task.</p>
                                </div>`
                            )
                        } else {
                            tasks.map(task => makeTaskCard(task))
                        }
                    }, 
                    error: (err) => {
                        console.log(err)
                    }
                }
            )
        }

        const toggleTask = (pk) => {
            $.ajax(
                {
                    url: `toggle-task/${pk}`,
                    type: "POST",
                    dataType: "json",
                    data: {
                        csrfmiddlewaretoken: "{{csrf_token}}"
                    },
                    success: (task) => {
                        if (task.fields.is_finished) {
                            $(`#task-${pk}`).removeClass("border-red-600").addClass("border-green-600");
                            $(`#task-${pk}-text`).addClass("line-through decoration-slate-500")
                        } else {
                            $(`#task-${pk}`).removeClass("border-green-600").addClass("border-red-600");
                            $(`#task-${pk}-text`).removeClass("line-through decoration-slate-500")
                        }
                    }, 
                    error: (err) => {
                        console.log(err)
                    }
                }
            )
        }

        const deleteTask = (pk) => {
            $.ajax(
                {
                    url: `delete/${pk}`,
                    type: "DELETE",
                    dataType: "json",
                    headers: {"X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()},
                    success: (tasks) => {
                        $(`#task-${pk}`).remove()
                        if (tasks.length == 0) {
                            const taskSection = document.querySelector(".tasks")
                            taskSection.insertAdjacentHTML('beforeend', 
                                `<div class="animation my-4 grid place-items-center">
                                    <lottie-player src="https://assets9.lottiefiles.com/datafiles/vhvOcuUkH41HdrL/data.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player>
                                    <p>Waduh, kamu belum punya task.</p>
                                </div>`
                            )
                        }
                    }, 
                    error: (err) => {
                        console.log(err)
                    }
                }
            )
        }

        $(document).ready(() => {
            getTasks()
        });

        {% comment %} Source: https://www.section.io/engineering-education/creating-a-modal-dialog-with-tailwind-css/ {% endcomment %}
         window.onload = () => {
            const modal = document.getElementById("create-task-modal")
            const toggleModalBtn = document.getElementById("toggle-create-task-btn")
            const toggleTaskBtn = document.getElementById("toggle-task-btn")
            const deleteTaskBtn = document.getElementById("delete-task-btn")
            const createTaskBtn = document.getElementById("create-task-btn")
    
            toggleModalBtn.onclick = () => {
                modal.style.display = "flex"
            }

            window.onclick = (e) => {
                if (e.target === modal) {
                    modal.style.display = "none"
                }
            }

            createTaskBtn.onclick = (e) => {
                e.preventDefault();
                $.ajax(
                    {
                        url: "{% url 'todolist:create_task_ajax' %}",
                        type: "POST",
                        dataType: "json",
                        data: $('form#create-task-form').serialize(),
                        success: (task) => {
                            $('#create-task-form').trigger("reset");
                            if ($(".animation").length) {
                                $(".animation").remove()
                            }
                            makeTaskCard(task)
                            modal.style.display = "none"
                        }, 
                        error: (err) => {
                            console.log(err)
                        }
                    }
                )
            }
 
        }
    </script>

    <nav class="bg-black text-white px-6 py-4 flex justify-between items-center mb-16">
        <p class="text-2xl font-bold">To Do List</p>
        <div class="flex justify-center items-center gap-6">
            <strong>Halo, {{ user.username }}!</strong>
            <a class="px-4 py-2 bg-red-600 rounded-lg" href="{% url 'todolist:logout' %}">Logout</a>
        </div>
    </nav>
    
 <section class="flex flex-col items-center justify-center mb-16">
    <div class="tasks w-full flex flex-col items-center justify-center">
    </div>

    <button id="toggle-create-task-btn" class="px-4 py-2 bg-black text-white rounded-lg">Tambah Task</button>

    <div id="create-task-modal" class="hidden backdrop-brightness-50 backdrop-blur-sm w-screen h-screen fixed justify-center items-center top-0 left-0">
        <div class="fixed bg-white p-10 rounded-xl container max-w-screen-sm max-h-screen">
            <p class="text-xl font-bold mb-4">Buat Task Baru</p>
            <form id="create-task-form" class="w-full" method="POST" action="">
                {% csrf_token %}
                <label class="mb-4">Judul</label><br>
                <input class="w-full rounded-lg border-2 border-black mb-4" type="text" name="title" placeholder="Belajar SDA" required/><br>
                    
                <label class="mb-4">Deskripsi</label><br>
               <textarea class="w-full rounded-lg border-2 border-black mb-4" name="description" placeholder="Binary Search Tree, Sorting" required></textarea><br>
        
                <input id="create-task-btn" class="cursor-pointer px-4 py-2 bg-black text-white w-full rounded-lg" type="submit" value="Tambah!">
            </form>
          </div>
    </div>

</section>


 {% endblock content %}

todolist/templates/todolist/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login | To Do List</title>
{% endblock meta %}

{% block content %}
<nav class="text-xl font-bold px-8 pt-4 md:text-2xl sticky top-0">To Do List</nav>
<section class="flex items-center justify-center h-screen gap-12 px-8">
    <div class="w-full md:w-2/3 lg:w-1/2 p-4 flex flex-col gap-8">
        <p class="text-3xl font-bold">Siap produktif, nih :)</p>
    <form class="w-full" method="POST" action="">
        {% csrf_token %}
        <label class="mb-4">Username</label><br>
        <input class="w-full rounded-lg border-2 border-black mb-4" type="text" name="username" placeholder="Enter your username" required><br>
            
        <label class="mb-4">Password</label><br>
        <input class="w-full rounded-lg border-2 border-black mb-4" type="password" name="password" placeholder="**********" required><br>

        <input class="px-4 py-2 bg-black text-white w-full rounded-lg" type="submit" value="Login">
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
            <p class="px-4 py-3 border border-2 border-black rounded-lg text-center">
                {{ message }}
            </p>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p>Belum mempunyai akun? <a class="text-blue-600 underline" href="{% url 'todolist:register' %}">Buat Akun</a></p>
    </div>
    <lottie-player class="hidden md:block md:w-1/3 lg:w-1/2" src="https://assets9.lottiefiles.com/packages/lf20_ipcfpsml.json"  background="transparent"  speed="1"  loop  autoplay></lottie-player>
</section>

{% endblock content %}

todolist/templates/todolist/register.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block meta %}
<title>Registrasi Akun | To Do List</title>
{% endblock meta %}

{% block content %}  
<nav class="text-xl font-bold px-8 pt-4 md:text-2xl sticky top-0">To Do List</nav>


<section class="flex items-center justify-center h-screen gap-4">
    <div class="hidden md:flex w-1/2 flex-col items-center justify-center h-screen">
        <lottie-player class="h-3/4" src="https://assets3.lottiefiles.com/packages/lf20_wtwlbhcf.json"  background="transparent"  speed="1"  loop  autoplay></lottie-player>
    </div>
    <div class="px-16 py-8 w-full md:w-1/2 h-screen flex flex-col items-center justify-center">
        <p class="text-2xl font-bold mb-5">Registrasi Akun</p>  

        <form class="w-full" method="POST">
            {% csrf_token %} 
            {% for field in form %}
            <div>
                {{ field.label_tag }}<br>
                {{ field | add_class:"w-full border-2 border-black rounded-lg mb-3"}}
                {{ field.errors }}
            </div>
            {% endfor %}
            <input class="w-full px-4 py-2 bg-black text-white rounded-lg my-4" type="submit" name="submit" value="Daftar"/>
        </form>

        {% if messages %}  
            <ul> 
                {% for message in messages %}
                    <p class="px-4 py-3 border border-2 border-red-500 text-red-500 text-center">{{ message }}</p>
                {% endfor %}
            </ul>   
        {% endif %}

        <p>Sudah mempunyai akun? <a class="text-blue-600 underline" href="{% url 'todolist:login' %}">Masuk</a></p>
    </div>
    

</section>  

{% endblock content %}